spring:
  profiles:
    active: @env@
  application:
    name: backend-service
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 10MB

server:
  error:
    include-stacktrace: never
    include-binding-errors: always
    include-message: always
    include-exception: true
  port: ${PORT:8080}

jwt:
  publicKey: "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmGnl1AF94jpSvGu3PMWnMvxOFRzLeAgbnn/afL18LdPE5wMl5XtD8ysEUkPB0z5SU3ye0ByfAIMTVIoihi1nJR6gUeIogazm6tKmFucdBj8Adxh+uXPlQ/GJz6wlvvz+k2NOo5y9JUZGHfT3HNxlm4PB9Y9wMqKyOd3IsM2z/UEYbx06aV/uWJxbTJZOx9z3W7/P0BXxM38BSvjkt2FdMUH/40G6TgMsrEi83kk3M+A3ulJnH/9RqgLesP+7ia3qZqNfn6aKMm2ZVxA6ZzmOkTFkRJb1XqFUn7KmevKcnG4z2mjR5tCJc3mpJAXPob/k/qMxFgTRt6RXmCsFfFzkISHAyib8CI6FW+GCq1//wHHovdbXvbzvKCszZr2eTZZSANVC6vOhpTHxpVFzd+5Sml1h3D5+BG/klNtqGO6Y9x4ZOstpE1+WBrDDyiCIwSjbwmx/9VvTCu2HtCMZQLtXYT1troZyO8Oq/k3puJe1U6cQPBNLKJ0HOgfPFmE6NQA9sOrIWhKCrksthQHAlqLSVHJ7jDKhOIvZ7r5fWwLoO/HfYHWRrlj/SGNa8t+QXdIai+fEFOsLdN6+WP48tcD73gx8ggEJe4v0YZkqDEuyUOmh8fFqB6jTv53iALovL6C72/gjDxnOQPSlaP2/HS3kq2fS1SJr8G9OaRRBeqvs0r0CAwEAAQ=="
  privateKey: "MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCYaeXUAX3iOlK8a7c8xacy/E4VHMt4CBuef9p8vXwt08TnAyXle0PzKwRSQ8HTPlJTfJ7QHJ8AgxNUiiKGLWclHqBR4iiBrObq0qYW5x0GPwB3GH65c+VD8YnPrCW+/P6TY06jnL0lRkYd9Pcc3GWbg8H1j3AyorI53ciwzbP9QRhvHTppX+5YnFtMlk7H3Pdbv8/QFfEzfwFK+OS3YV0xQf/jQbpOAyysSLzeSTcz4De6Umcf/1GqAt6w/7uJrepmo1+fpooybZlXEDpnOY6RMWRElvVeoVSfsqZ68pycbjPaaNHm0IlzeakkBc+hv+T+ozEWBNG3pFeYKwV8XOQhIcDKJvwIjoVb4YKrX//Acei91te9vO8oKzNmvZ5NllIA1ULq86GlMfGlUXN37lKaXWHcPn4Eb+SU22oY7pj3Hhk6y2kTX5YGsMPKIIjBKNvCbH/1W9MK7Ye0IxlAu1dhPW2uhnI7w6r+Tem4l7VTpxA8E0sonQc6B88WYTo1AD2w6shaEoKuSy2FAcCWotJUcnuMMqE4i9nuvl9bAug78d9gdZGuWP9IY1ry35Bd0hqL58QU6wt03r5Y/jy1wPveDHyCAQl7i/RhmSoMS7JQ6aHx8WoHqNO/neIAui8voLvb+CMPGc5A9KVo/b8dLeSrZ9LVImvwb05pFEF6q+zSvQIDAQABAoICAQCWz7JqpU86mxti9fLKX4miGaXpniR3EQ7DNx+qbpSBhBpBvAuzltUVuGr+O61+qRwtIBLFOozapNhrvoOK4UI+qJ9aZr5OEhgsI2PVJbrCg3SiY8qBFvy0zjvfEigHY69Dh/A4VM+UIoUe/1XFaQ/hYe56XQRYFkTknWAIEoMXBWJ4ECPMQPBHHe/5SIGLokngr1uiOxQAMJvG46DtE5pzMytQY6lFqD57+z1ndmr5GdQKuZ7xOmJEJ7LS0TlwcnaOOPpVryTv4SLp01T27yzy3jyo4fbJPDnQC6ZP4eC1qRYF99I64f4gFTIYQufA1XBxxmi7sOkTHbrPB0LWW9QepNf3qUOMXHeHrvCs6ikNu+3QrKUtYr8XepHQ99RslVkXbl9TGC4EJdJ7Htjql/lLQ61GvxNHuqTlL5jygf+9BAZKVcd0nyyK392mJUk+q8D5rX7ubhRSWatkIECdxCCjsV0dEwsTsOSpGpnjV6xJY1P9jatepqUDYVSNYl1tD6mb4iu8EMpBZa8iBjkQges/LQXcB7P0xtT8x34ufY+j8sJQG3b/OP16Y3p1CkXBJfMI97PM8oKjZpCMXYkaHBsXg7c0IROGxv1lWCo1n6u8zfQz5VYcjXf8WmAICSr4rC1rIPMvxWKy0FRYeThyVv+wE4JP8AIpVOxENVxxijZAwQKCAQEA9DsE+14i8kEaSN/JRfeL58ougr53j1oKoAnErYkY7gRm5/57O3Ck90GlhkSqGscWix0SHh1CayBMO8xBdDzdTlJ6gMYd7cOgMuyRmYxAa5hbuBi3H5sK3dJKRqbyhnwouFM9R7OvU6P8Q+fqXhnaT+DzptLDzBrRbj30oUmS3EbcuVRxWMKC8Bac4tVF/WfFYFt2q1daGcnP4DEPVDG7XfF5jLWsO/OuJaKmz+b5qdOA7SZKguUNfvym+QAL2qdNYiYgbzqJXresD4shrBwV7iTwLxOIZB6JU4vDESeiRHiaM/Pvaee/Y4FgUxq+dHPliWS9N6p6gfme95JfsZ6MtwKCAQEAn8Iq/AK/BIiVEoIOBTpTV+wbIVsM68fLhQ/xe+GFV15qVebi1hArq5jQit3rARH58sOUc8bdoQuonRjwMdb0+QJB2sSFPaUCdJXSwo0xo68CeI3J5o8JizOPFNUZsv/TEnWHmq13zJdsJ+8+ZYHTWXgLFfb8tyNyfc6YN2bgfnNXRfNhEKNbvS3+dZktKxYK1nrAJD+2rGMaRViXXmB32hQq4cHRCSl3Hl80GovZV4HJ8RdspdyrTRugyNTbRc/4sx9FnmkoxXGXUtwxhDtaReP0lWOw1lgSJtp+rpNzf5wpZE8lBaqIL+eNUZQXaloyHib1S2MO4U7hGNQXej5QKwKCAQB6fG8PMjMMlCH+kl17PZ9o7DlPUP7dYicaBEwjTDK4jHSfvT1InkHdz4qYQC+fpmFj+3xupfX9jAEvrEzXYv8KnMrbcoDoEchyQbrz6ycTzyGQvrR4oWVdwm2F6YyQbgxuBTEimLdBl2iZFeKwtv6KOSN5cxLHdlu6kk/x49hHqTJhsDv4a/UHPBAKozOq1zRiEvz9CZ4ieNhMc85gR2DUyJpRO3vZxWh9b4mBkzF7PpvWU/Him8Wc/lEvaBqJ2oYwxzZVEmJ6olskoH6Otrc47EWZFo68x6PPxrRaEiqLdIDBtYFI9/VAjk4k37DM7qMbuO480L8IGIzlVP+xMPcZAoIBAHumKObMqVO08sxUZM2fCwqt74Gtmx6SkO74HAupzS6GIP9DqKXN9j7mE+KnSFCXvUEsJyZE8RzIjUSqHJ42pXxlRtsv54CCype5rlpuNdFejycHdxE//D8FNOUG2tE0OAW9eas6P9LWEBwIi9680PwacVoaxBZrFR5SXHXk5jR4yT+W07Ww+jw98QjL+a2zbcf7UeO8fIKIYbjyjJW7TIg5u8bn4AabVVrojMdPHnUgO1CitLDbTqpri9JlDSHHidH5jkTBV5EaDelQC/MwjPozKQbHFgOQPtxbmFk+PtKx50eACkOMbcPGEBbn7Aegr9GujYQ/szCngIla/qDawekCggEBAKFc6BopjO316jcaXlrfE4jGaPVQmYfDZMQoI9gkwk7SESNufm437BdwcElCIXtMlFnoL+XlFHJeZVQ/gwVPkjoxPJvGfG03g8BSmZfbQfZNHGq2wF9LqESq+3tx3Xax87C7ZWzBevMLmSmpzWn1xCLTZf/YjKUS74+aexFdAI9wlXBMeL7HYCezpO362p17cqursblhr4Bw562uP9cMG/eeDVUR+TsZapNJYP2EMDGkTZE8v0Txp5N/8fGVyxLVRDc5/yADmsXUrREA/5lMq+fJEAZQ3xegdvf5i8jvIXS/3royfcHMQ2UyPH25J51+TZNj9dJcoUXSyuQ8RnSyETQ="
  expirationDateInMs: 400000000
  refreshExpirationDateInMs: 400000000

clubhouse:
  API_URL: "https://www.clubhouseapi.com/api"
  API_BUILD_ID: 304
  API_BUILD_VERSION: "0.1.28"
  API_UA: clubhouse/${clubhouse.API_BUILD_ID} (iPhone; iOS 14.4; Scale/2.00)

  PUBNUB_PUB_KEY: "pub-c-6878d382-5ae6-4494-9099-f930f938868b"
  PUBNUB_SUB_KEY: "sub-c-a4abea84-9ca3-11ea-8e71-f2b83ac9263d"
  TWITTER_ID: "NyJhARWVYU1X3qJZtC2154xSI"
  TWITTER_SECRET: "ylFImLBFaOE362uwr4jut8S8gXGWh93S1TUKbkfh7jDIPse02o"
  AGORA_KEY: "938de3e8055e42b281bb8c6f69c21f78"
  SENTRY_KEY: "5374a416cd2d4009a781b49d1bd9ef44@o325556.ingest.sentry.io/5245095"
  INSTABUG_KEY: "4e53155da9b00728caa5249f2e35d6b3"
  AMPLITUDE_KEY: "9098a21a950e7cb0933fb5b30affe5be"
  LOCAL_WS_AGORA_URL: "ws://localhost:8765/"

app:
  mock_enable: false
  mock_cookie: d7949e3801f62c89d21196ed4d076990958db24bfa6